### ISSUE TITLE
拡張編集フィルタの上限

### ISSUE THREAD

**Issue by nazonoSAUNA** [karoterra/aviutl_ShowLimit#15]
読み込まれた数：exedit92 + 0x146248
読み込まれたフィルタ情報（LoadedFilterTable）：exedit92 + 0x187c98
上限数：512（LoadedFilterTableの配列数が512のため）

現状としてこの上限がそこまで重要になることは無いはずですが、今後のpatch.aulで拡張編集用フィルタプラグインを読み込むような仕組みを作ることで増える可能性があるため情報として書きました

**Comment by karoterra** [comment]
情報提供ありがとうございます。
読み込まれた拡張編集フィルタの数を表に追加で表示するようにしてみました。
[Release v0.5.0 · karoterra/aviutl_ShowLimit](https://github.com/karoterra/aviutl_ShowLimit/releases/tag/v0.5.0)

aufなどと同様に拡張編集フィルタについても一覧を出力する機能を実装してみようかと思いましたが、その一覧をどうやって取得すればよいかすぐには分からなかったため、一旦見送りとしました。
ちなみにこちらについては、 `aviutl_exedit_sdk` の `ExEdit::Filter[512]` という理解であってますでしょうか。
> 読み込まれたフィルタ情報（LoadedFilterTable）：exedit92 + 0x187c98

**Comment by karoterra** [comment]
```c++
ExEdit::Filter LoadedFilterTable[512]   // こちらではなく
ExEdit::Filter *LoadedFilterTable[512]  // こっち
```
もしかしてこうですかね

**Comment by nazonoSAUNA** [comment]
https://github.com/nazonoSAUNA/patch.aul/blob/r43_58/patch/patch_exfilter.hpp
このあたりの使い方が参考になりますか？

後者で、厳密には`flag`に`ExEdit::Filter::Flag::ExEditFilter`があれば`ExEdit::Filter*`で、
なければ`AviUtl::Filter*`だったと思いますが、今回は特に区別しなくても使えそうな気はします

**Comment by nazonoSAUNA** [comment]
もう少し通常な使い方をしている方も貼っておきます
https://github.com/nazonoSAUNA/SortEffect/blob/main/src.cpp#L200

**Comment by karoterra** [comment]
ありがとうございます。
拡張編集フィルタの一覧も出力できるようになったので v0.5.1 としてリリースしました。
[Release v0.5.1 · karoterra/aviutl_ShowLimit](https://github.com/karoterra/aviutl_ShowLimit/releases/tag/v0.5.1)
